"""add confirmed to users

Revision ID: 681667b27fc7
Revises: 754faec83ba4
Create Date: 2018-11-26 21:33:16.423098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '681667b27fc7'
down_revision = '754faec83ba4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('confirmed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'confirmed')
    # ### end Alembic commands ###
