"""add user about me

Revision ID: 754faec83ba4
Revises: 17c71592addd
Create Date: 2018-11-25 01:01:10.136250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '754faec83ba4'
down_revision = '17c71592addd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
