"""empty message

Revision ID: be0faacc1606
Revises: fc0cfb4f1fe7
Create Date: 2019-04-14 21:09:21.658870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be0faacc1606'
down_revision = 'fc0cfb4f1fe7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('height', sa.BigInteger(), nullable=True))
    op.add_column('images', sa.Column('sizes', sa.JSON(), nullable=True))
    op.add_column('images', sa.Column('width', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('images', 'width')
    op.drop_column('images', 'sizes')
    op.drop_column('images', 'height')
    # ### end Alembic commands ###
