"""empty message

Revision ID: cc56507e2df3
Revises: eb425fdb2449
Create Date: 2019-07-07 11:52:18.490798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc56507e2df3'
down_revision = 'eb425fdb2449'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('otp_secret', sa.String(length=16), nullable=True))
    op.create_index(op.f('ix_users_otp_secret'), 'users', ['otp_secret'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_otp_secret'), table_name='users')
    op.drop_column('users', 'otp_secret')
    # ### end Alembic commands ###
